//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Térképszerkesztő.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Térképszerkesztő.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Height (Horizontal dimension) : (Minimum : 5).
        /// </summary>
        internal static string askHeightENG {
            get {
                return ResourceManager.GetString("askHeightENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pálya magassága (Horizontális méret) : (Minimum : 5).
        /// </summary>
        internal static string askHeightHU {
            get {
                return ResourceManager.GetString("askHeightHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Main Menu
        ///2) Proceed to map editor.
        /// </summary>
        internal static string askNextENG {
            get {
                return ResourceManager.GetString("askNextENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Vissza a főmenübe
        ///2) Tovább a pályaszerkesztőhöz.
        /// </summary>
        internal static string askNextHU {
            get {
                return ResourceManager.GetString("askNextHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of save : (Default : Documents folder).
        /// </summary>
        internal static string askSaveENG {
            get {
                return ResourceManager.GetString("askSaveENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés helye : (Alap : Dokumentumok mappa).
        /// </summary>
        internal static string askSaveHU {
            get {
                return ResourceManager.GetString("askSaveHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Width (Vertical dimension) : (Minimum : 5).
        /// </summary>
        internal static string askWidthENG {
            get {
                return ResourceManager.GetString("askWidthENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pálya szélessége (Vertikális méret) : (Minimum : 5).
        /// </summary>
        internal static string askWidthHU {
            get {
                return ResourceManager.GetString("askWidthHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width: {0} Height: {1}.
        /// </summary>
        internal static string cordsENG {
            get {
                return ResourceManager.GetString("cordsENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szélesség: {0} Magasság: {1}.
        /// </summary>
        internal static string cordsHU {
            get {
                return ResourceManager.GetString("cordsHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your map must contain a minimum of 1 room and 2 exits..
        /// </summary>
        internal static string errorENG {
            get {
                return ResourceManager.GetString("errorENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pályában muszáj minimum 1 szobának, és 2 kijáratnak lennie..
        /// </summary>
        internal static string errorHU {
            get {
                return ResourceManager.GetString("errorHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of placed exits: {0}.
        /// </summary>
        internal static string exfilENG {
            get {
                return ResourceManager.GetString("exfilENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijáratok száma: {0}.
        /// </summary>
        internal static string exfilHU {
            get {
                return ResourceManager.GetString("exfilHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Exit
        ///2) Save map to file and exit.
        /// </summary>
        internal static string exitENG {
            get {
                return ResourceManager.GetString("exitENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Kilépés
        ///2) Fáljba mentés és Kilépés.
        /// </summary>
        internal static string exitHU {
            get {
                return ResourceManager.GetString("exitHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Movement: WASD | Placing components : 0-9 |.
        /// </summary>
        internal static string info1ENG {
            get {
                return ResourceManager.GetString("info1ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Mozgás : WASD | Pályaelemek letétele : 0-9 |
        ///.
        /// </summary>
        internal static string info1HU {
            get {
                return ResourceManager.GetString("info1HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Crossroad: K | Room : T |.
        /// </summary>
        internal static string info2ENG {
            get {
                return ResourceManager.GetString("info2ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Kereszteződés : K | Terem : T |.
        /// </summary>
        internal static string info2HU {
            get {
                return ResourceManager.GetString("info2HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Settings : B | Quit : Q |.
        /// </summary>
        internal static string info3ENG {
            get {
                return ResourceManager.GetString("info3ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Beállítások : B | Kilépés : Q |.
        /// </summary>
        internal static string info3HU {
            get {
                return ResourceManager.GetString("info3HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Language : {0} | Delete : Backspace |.
        /// </summary>
        internal static string info4ENG {
            get {
                return ResourceManager.GetString("info4ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Nyelv : {0} | Törlés : Backspace |.
        /// </summary>
        internal static string info4HU {
            get {
                return ResourceManager.GetString("info4HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labyrinth Game | Map Maker
        ///Press any key to continue!.
        /// </summary>
        internal static string landPageTextENG {
            get {
                return ResourceManager.GetString("landPageTextENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labirintus Játék | Térkép Készítő 
        ///Nyomjon egy gombot a továbblépéshez!.
        /// </summary>
        internal static string landPageTextHU {
            get {
                return ResourceManager.GetString("landPageTextHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed Rooms : {0}.
        /// </summary>
        internal static string roomENG {
            get {
                return ResourceManager.GetString("roomENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elhelyezett termek száma: {0}.
        /// </summary>
        internal static string roomHU {
            get {
                return ResourceManager.GetString("roomHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (To navigate the menu, enter a number and press ENTER!)
        ///1) Language
        ///2) Customize map
        ///3) Map Editor (Default map size : (7*25)).
        /// </summary>
        internal static string settingsENG {
            get {
                return ResourceManager.GetString("settingsENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (A menük navigálásához válaszoljon számmal majd nyomjon ENTER-t!)
        ///1) Nyelvválasztás
        ///2) Saját pálya készítése
        ///3) Pálya Betöltése (Alapértelmezett pálya mérete : (6*24)).
        /// </summary>
        internal static string settingsHU {
            get {
                return ResourceManager.GetString("settingsHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        internal static string tempExENG {
            get {
                return ResourceManager.GetString("tempExENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés....
        /// </summary>
        internal static string tempExHU {
            get {
                return ResourceManager.GetString("tempExHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved..
        /// </summary>
        internal static string tempSaveENG {
            get {
                return ResourceManager.GetString("tempSaveENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl elmentve..
        /// </summary>
        internal static string tempSaveHU {
            get {
                return ResourceManager.GetString("tempSaveHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Maker - Main Menu.
        /// </summary>
        internal static string title1ENG {
            get {
                return ResourceManager.GetString("title1ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Térképszerkesztő - Főmenü.
        /// </summary>
        internal static string title1HU {
            get {
                return ResourceManager.GetString("title1HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Maker - Settings.
        /// </summary>
        internal static string title2ENG {
            get {
                return ResourceManager.GetString("title2ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Térképszerkesztő - Beállítások.
        /// </summary>
        internal static string title2HU {
            get {
                return ResourceManager.GetString("title2HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Maker - Language.
        /// </summary>
        internal static string title3ENG {
            get {
                return ResourceManager.GetString("title3ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Térképszerkesztő - Nyelvválasztás.
        /// </summary>
        internal static string title3HU {
            get {
                return ResourceManager.GetString("title3HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Maker - Custom Map Maker.
        /// </summary>
        internal static string title4ENG {
            get {
                return ResourceManager.GetString("title4ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Térképszerkesztő - Saját pálya készítés.
        /// </summary>
        internal static string title4HU {
            get {
                return ResourceManager.GetString("title4HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Maker.
        /// </summary>
        internal static string title5ENG {
            get {
                return ResourceManager.GetString("title5ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Térképkészítő.
        /// </summary>
        internal static string title5HU {
            get {
                return ResourceManager.GetString("title5HU", resourceCulture);
            }
        }
    }
}
